name: Deploy User-Defined Function

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install snowflake-connector-python
    - name: Download Update UDF script
      run: |
        curl -o $PWD/update_udfs.py https://raw.githubusercontent.com/iamontheinet/c-i-c-d/main/update_udfs.py
    - name: Deploy UDF
      env:
        SNOWSQL_ACT: ${{ secrets.account }}
        SNOWSQL_USR: ${{ secrets.user }}
        SNOWSQL_PWD: ${{ secrets.password }}
        SNOWSQL_ROL: ${{ secrets.role }}
        SNOWSQL_DBT: ${{ secrets.database }}
        SNOWSQL_WRH: ${{ secrets.warehouse }}
        SNOWSQL_SCH: ${{ secrets.schema }}
      run: |
        python update_udfs.py
